# Generated by Django 5.1.3 on 2024-11-25 04:08

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.FileField(default='default_user.png', upload_to=home.models.image),
        ),
    ]
